version: '3'
services:
  server:
    build: .
    command: node_modules/nodemon/bin/nodemon.js --watch 'src/**/*.ts' --exec 'node_modules/ts-node/dist/bin.js' src/index.ts
    ports:
      - 8080:8080
    volumes:
      - .:/server/
    tty: true
    depends_on:
      - postgres
      - mongodb
    env_file:
      - .env
  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    env_file:
      - .env
  mongodb:
    image: mongo:3.6.1
    ports:
      - 27017:27017
    restart: always
    env_file:
      - .env
